-- ============================================================================
-- GOLD — dim_macro_environment (managed externally)
-- ============================================================================
-- This Delta table is written directly by `data/generators/00_macro_environment.py`
-- and is NOT (re)declared by the Lakeflow pipeline. The empty body is intentional —
-- it leaves the table untouched by pipeline refreshes so the AR(1) noise sequence
-- stays deterministic across pipeline runs.
--
-- Querying: SELECT * FROM ${catalog}.${schema_gold}.dim_macro_environment;
-- ============================================================================
